meta_inspector:
  user_agent: 'facebookexternalhit/1.1 (+http://www.facebook.com/externalhit_uatext.php)'
site:
  aibot_address: 'http://localhost:3000/aichatbot'
messages_filter:
  messages_display_number_filter: 5 # display_number: 5%, digest_number: 95%
